apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-python-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-python-app
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
